# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
    ]
