# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 21:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kredit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kredit',
            options={'verbose_name': 'Kredit', 'verbose_name_plural': 'Kredits'},
        ),
        migrations.AddField(
            model_name='kredit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 21, 0, 52, 690000, tzinfo=utc), verbose_name='Creation data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kredit',
            name='current_level',
            field=models.CharField(choices=[('0', '\u041a\u0440\u0435\u0434\u0438\u0442\u0447\u0438\u043a\u0438'), ('1', '\u0421\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u0442\u0435\u043b\u0438'), ('2', '\u0411\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c'), ('3', '\u0414\u0421\u041a\u041f \u0412\u044b\u0434\u0430\u0447\u0430')], default='0', max_length=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='db_status',
            field=models.CharField(choices=[('0', '\u0420\u0435\u0448\u0435\u043d\u0438\u044f \u043d\u0435\u0442'), ('A', '\u041e\u0434\u043e\u0431\u0440\u0435\u043d'), ('R', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d')], default='0', max_length=1, verbose_name='DB status'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='doc_complect',
            field=models.CharField(choices=[('1', '\u043f\u0435\u0440\u0432\u044b\u0439'), ('2', '\u0432\u0442\u043e\u0440\u043e\u0439')], default='1', max_length=1, verbose_name='Complect'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='dskp_status',
            field=models.CharField(choices=[('0', '\u0420\u0435\u0448\u0435\u043d\u0438\u044f \u043d\u0435\u0442'), ('A', '\u041e\u0434\u043e\u0431\u0440\u0435\u043d'), ('R', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d')], default='0', max_length=1, verbose_name='DSKP status'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='kred_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='kred_mode',
            field=models.CharField(choices=[('A', '\u042d\u041a\u0421\u041f\u0420\u0415\u0421\u0421-\u041d\u0410\u041b\u0418\u0427\u041d\u042b\u041c\u0418'), ('B', '\u041d\u0410\u0428 \u041f\u0415\u041d\u0421\u0418\u041e\u041d\u0415\u0420'), ('C', '\u041d\u0411\u041a\u0418')], default='A', max_length=1, verbose_name='Kredit kind'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kredit.Kredit', verbose_name='Link to other complect'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='office',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Bank.Office', verbose_name='Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kredit',
            name='secondname',
            field=models.CharField(default='', max_length=512, verbose_name='Second Name'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='sess',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='status',
            field=models.CharField(choices=[('N', '\u041d\u043e\u0432\u0430\u044f'), ('D', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u0430'), ('A', '\u041e\u0434\u043e\u0431\u0440\u0435\u043d\u0430'), ('R', '\u041d\u0430 \u0440\u0430\u0441\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0438'), ('T', '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435 \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438'), ('B', '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e \u043d\u0430 \u0434\u043e\u0440\u0430\u0431\u043e\u0442\u043a\u0443'), ('C', '\u041d\u0430 \u0434\u043e\u0440\u0430\u0431\u043e\u0442\u043a\u0443 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u0442\u0435\u043b\u044e'), ('F', '\u0414\u043e\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043e'), ('M', '\u041f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0434\u043e\u0440\u0430\u0431\u043e\u0442\u043a\u0430')], default='N', max_length=1, verbose_name='Kredit status'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='sum',
            field=models.FloatField(default=0, verbose_name='Sum'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='surname',
            field=models.CharField(default='', max_length=512, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='kredit',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
            preserve_default=False,
        ),
    ]
