# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('kredit', '0003_sessionfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredit',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='Groups'),
        ),
    ]
